#!/bin/bash
# Example workflow for setting up memory configuration
# This file is for reference only - shows typical usage

echo "=== Example Workflow for 128GB System ==="
echo ""
echo "Step 1: Check current configuration"
echo "$ make check-memory-config"
echo ""
echo "Step 2: Set memory to 16GB (recommended)"
echo "$ make set-memory-16gb"
echo ""
echo "Step 3: Verify the configuration"
echo "$ make check-memory-config"
echo ""
echo "Step 4: Start your services normally"
echo "$ make standard"
echo "  (or backend-only, minimal, standard-gpu, etc.)"
echo ""
echo "Step 5: Monitor memory during operation"
echo "$ curl http://localhost:3005/api/health/memory | jq"
echo ""
echo "=== To change memory allocation later ==="
echo "$ make set-memory-32gb    # Increase to 32GB"
echo "$ make down               # Stop services"
echo "$ make standard           # Restart with new memory"
echo ""
echo "=== Available presets ==="
echo "$ make set-memory-8gb     # 8GB  - Light usage"
echo "$ make set-memory-16gb    # 16GB - Recommended"
echo "$ make set-memory-32gb    # 32GB - High volume"
echo "$ make set-memory-64gb    # 64GB - Maximum"
echo ""
echo "=== Custom size ==="
echo "$ ./set-memory.sh 20480   # 20GB custom"

