#!/bin/bash

echo "════════════════════════════════════════════════════════════════"
echo "  Memory Diagnostics Status Check"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Run these commands on your remote server:"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo "1. Check if environment variable is set in container:"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "docker exec <container-name> env | grep MEMORY_DIAGNOSTICS"
echo ""
echo "Expected: MEMORY_DIAGNOSTICS_ENABLED=true"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo "2. Check container logs for diagnostic initialization:"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "docker logs <container-name> | grep -i 'memory diagnostic'"
echo ""
echo "Expected to see:"
echo "  ✅ [Memory Diagnostics] Initialized successfully"
echo "  OR"
echo "  ⚠️ [Memory Diagnostics] MEMORY_DIAGNOSTICS_ENABLED is not set"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo "3. Check if log file exists and is being written:"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "ls -lh logs/memory-diagnostics.log"
echo "date"
echo ""
echo "The file timestamp should be recent (within last few minutes)"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo "4. Trigger some activity to generate diagnostic entries:"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "Make a few API requests from FitnessAlly app, then:"
echo ""
echo "tail -20 logs/memory-diagnostics.log"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo "5. Force immediate diagnostic output (debug mode):"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "Watch container logs in real-time:"
echo ""
echo "docker logs -f <container-name> | grep -E '(Memory Monitor|Heap:)'"
echo ""
echo "You should see memory snapshots every 3 minutes like:"
echo ""
echo "  [Memory Monitor] Heap: 250MB / 270MB, RSS: 500MB, External: 50MB"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "IMPORTANT:"
echo "  - Memory diagnostics logs periodically (every 60 seconds)"
echo "  - It ONLY writes to memory-diagnostics.log when growth is detected"
echo "  - At 300MB startup, there may not be much to report yet"
echo "  - Use the app for 15-30 minutes, THEN check the log"
echo ""
echo "════════════════════════════════════════════════════════════════"
