version: "3.8"

services:
  oip:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3005:3005"
      - "9229:9229"
    volumes:
      - ./media/jfk:/usr/src/app/media/jfk
    environment:
      - NODE_ENV=production
      - ELASTICSEARCH_HOST=${ELASTICSEARCHHOST}
      - ELASTICCLIENTUSERNAME=${ELASTICCLIENTUSERNAME}
      - ELASTICCLIENTPASSWORD=${ELASTICCLIENTPASSWORD}
    networks:
      - existing-oip-network
    restart: unless-stopped

networks:
  existing-oip-network:
    external: true
    name: oiparweave_oip-network