// /config/templates.config.js

module.exports = {
    defaultTemplates: {
        basic: "-9DirnjVO1FlbEW1lN8jITBESrTsQKEM_BoZ1ey_0mk",
        creatorRegistration: "BKVvTSXmmJni-L82irZfPFXWWJLBcdvbxS34jP1FTG8", 
        associatedURLOnWeb: "eVTn36AY0JdLI_jzj9FivxrxtvlkVQIPI5ma-1x0E2c",
        text: "of_eh0kGy65uYD0xsTh7Qe6JVTfJ2oFoA7xp4H7t7YI",
        image: "AkZnE1VckJJlRamgNJuIGE7KrYwDcCciWOMrMh68V4o",
        audio: "9MrI8kJvBJ-u7uvgngMZ-gMo5RREDwey8G7mJEUOpdo",
        video: "G73WplyxpNDOgDSFO6CP3O6hZXq8kNJXxkCqx3sgd1s",
        post: "op6y-d_6bqivJ2a2oWQnbylD4X_LH6eQyR6rCGqtVZ8",
        podcast: "MojoZlLKaH-cHy_HbaGBlBA7Mxzf8dJl4MQZzFQAkMY",
        jfkFilesPageOfDocument: "WP-tZ5nwxrMwr5wKHazTFUtGLRd6nQWRBl8E63Kqufg",
        jfkFilesDocument: "d3xoxXQ8hUlrgKTo1UZc4_GqaKTaApJs0tLFuK6Hxqk",
        exercise: "XVu78TY-4LX6-vOajc7AKAk9jn1amFSC87XMTGTz4Mw",
        workout: "yxguXXKD_YSnCjC1ILYFBmQ6F20F5dKOoA6hxuqhNUk",
        recipe: "SLsJ91-Z82rRBPkDrZlG87aIpbw6zOlmK96nh5uf6G4",
        nutritionalInfo: "_xuiAaVKxPL1Dsp-AceCpXqnc0C_WwHC-Ws1vN-cBUs",
        podcastShow: "JQ_gsZucnD5aM9V9ue748R5COGFyOZYstGVSm1iX7rU",
        modelProvider: "KiINbVeLPhF795ADmX7LM9oUuI7oAdBm1QtH5Ncj32I",
        conversationSession: "eb6irolDympa5_XENtWMIp_bvQ6CLI9q5arRIBTe2sk",
        multiResolutionGif: "5lqxoSI7DLsl9Q5nqCIsH53r2TUz_Eg6Z56nXc5pk4I",
        organization: "NQi19GjOw-Iv8PzjZ5P-XcFkAYu50cl5V_qceT2xlGM",
        fitnessEquipment: "VEz6iYZ8XpsOHQCOriv7gxyvY0OqyBXrNANCVHEgIsk",
        userFitnessProfile: "2_Jb98EGbZAtZRNrXXCQMTzg-_iYdGjh2qbnI-k-osE",
        workoutSchedule: "ACgUZxpsxhvy1TaXoOBMBgduje3-d8__gs9nPFSGXWM",
        mealPlan: "-roCasok1eDw_sjBec9KrGtzuCN5WqpKE15GNfYqsJ8",
        exerciseResult: "eZFqXh4O5zVqCEs2oNvhi5K3fi8VrTJ9kROVjYmEuxc",
        workoutCompletion: "C3BEhAF0_4Cbblo4CRp8585v6oyaPcgkpiKBp4jWQyw",
        weightEntry: "yXFy2izo1ALbAQOvl8qEQP2XpmMzZoUGXri72I-SKFY",
        shoppingList: "pBI0qarLBP6zPIxBPsl7-ZhzPo0VBqoQ0OFEwZQCUxQ",
        userFitnessAchievment: "-sC601MieajKTLtJfe0ZyT8zxC9SiDrOa8HTP9aOiU0"
    },
};